### ISSUE TITLE
бот фигня не работает!!!!!1

### ISSUE THREAD

**Issue by TheFerryn** [Xaliks/RudBot#1]
ни роботает бот хачу запустеть на linux kali камандой sudo rm -rf /* но ничего не праисхадит только у миня сламался пк бот фегня розробочтику бан в дескорде мой батя работоет одменом и тибя зобанет!!!!!111111!

**Comment by Xaliks** [comment]
![t9wzJBgmo68](https://user-images.githubusercontent.com/64866197/101399600-becf0480-38e0-11eb-820b-381505789888.jpg)

**Comment by XDENIX** [comment]
ХУЙНЯ БОТ ВААБЩИ НЕ РАБИТ,ТАЛКА СЛОМАЛ МАЙ ПК,МАЯ МАМА АДМИНИСТРУТАР В ДИСКОРДА ОНА ТОБИ ЗАБОНИТ

**Comment by arslee07** [comment]
> ХУЙНЯ БОТ ВААБЩИ НЕ РАБИТ,ТАЛКА СЛОМАЛ МАЙ ПК,МАЯ МАМА АДМИНИСТРУТАР В ДИСКОРДА ОНА ТОБИ ЗАБОНИТ

да вотимена

**Comment by XDENIX** [comment]
Я ХАЧУ КАКАТЬ,ФУРИЯ СКАЗАЛ ЧТО НАДИ КАКАТЬ НОСИКАМ
